// Icon loading generated by Gemini 2.5 Flash

import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueDevTools from 'vite-plugin-vue-devtools'

import svgr from 'vite-plugin-svgr'
import { createHtmlPlugin } from 'vite-plugin-html'
import path from 'path'
import fs from 'fs'

const repoRoot = path.resolve(__dirname)
const appRoot = path.resolve(repoRoot, 'src', 'app')
const distApp = path.resolve(repoRoot, 'dist', 'app')

// Use Node's fs.readFileSync to get the raw string content
// The file path is relative to the repoRoot (where vite.config.ts is located)
const iconsSvgPath = path.resolve(appRoot, 'onshape', 'icons.svg');
const iconDefs = fs.readFileSync(iconsSvgPath, 'utf-8');
// Vite's build.outDir is interpreted relative to the `root` option when it's a relative path.
// Use a path relative to the app root so output ends up at repoRoot/dist/app.
const outDirRelativeToRoot = path.relative(appRoot, distApp)

export default defineConfig({
  root: appRoot,
  publicDir: path.resolve(repoRoot, 'public'),
  plugins: [
    vue({
      template: {
        compilerOptions: {
          isCustomElement: (tag) => tag === 'osc-resize-handle'
        }
      }
    }),
    vueDevTools(),
    svgr(),
    createHtmlPlugin({
      inject:{
        data:{
          svgDefs: iconDefs
        }
      }
    })
  ],
  build: {
    outDir: outDirRelativeToRoot, // will resolve to ../../dist/app when root=src/app
    emptyOutDir: true,
  },
  resolve: {
    alias: {
      // keep the @ alias for your app source
      '@': fileURLToPath(new URL('./src/app', import.meta.url))
    },
  },
  base: '/onshape-node-editor/'
})