export type NodeFeaturescriptInfo = {
    line: string;
    dependencies?: Array<{path: string, version: string}>;
    preindent?: number;
    postindent?: number;
}

export class FeatureStudioGenerator {
    private version: string;

    constructor(version?: string) {
        this.version = version || "2960";
    }

    /**
     * Generate FeatureStudio code give NodeFeatureScriptInfo
     * Partially implemented by Claude Haiku 4.5
     * @param info 
     * @returns featurestudio code for a custom feature or custom function or both? (TODO)
     */
    public generateFeatureStudioCode(info: NodeFeaturescriptInfo[]) {
        // Collect all dependencies, avoiding duplicates by path
        const dependencyMap = new Map<string, {path: string, version: string}>();
        for (const item of info) {
            if (item.dependencies) {
                item.dependencies.forEach(dep => {
                    dependencyMap.set(dep.path, dep);
                });
            }
        }

        // Generate header
        let code = "// Generated by Onshape Node Editor\n// Edits will be overwritten by the Onshape Node Editor app\n";
        code += `FeatureScript ${this.version};\n`;

        // Add imports for dependencies
        if (dependencyMap.size > 0) {
            const sortedDeps = Array.from(dependencyMap.values()).sort((a, b) => a.path.localeCompare(b.path));
            for (const dep of sortedDeps) {
                code += `import(path : "${dep.path}", version : "${dep.version}");\n`;
            }
        } else {
            // Default import if no dependencies specified
            code += `import(path : "onshape/std/common.fs", version : "${this.version}.0");\n`;
        }

        code += "\n";

        let indents = 0;
        // Add feature studio lines with indentation
        for (const item of info) {
            indents += item.preindent ?? 0;
            const indent = "\t".repeat(Math.max(indents, 0));
            code += indent + item.line.replaceAll("\n", "\n" + indent) + "\n";
            indents += item.postindent ?? 0;
        }

        return code;
    }
}