<template>
  <div ref="socketContainer" class="socket-container">
    <div class="socket" :title="data.name"></div>
    <div class="snap-target" style="transform: translate(0%, 0%)"></div>
  </div>
</template>

<script lang="ts">
export default {
  props: ['data']
}
</script>

<style lang="scss" scoped>
@use "sass:math";
@use "./vars" as *;

.socket-container {
  z-index: 1;
  position: relative;
}

.socket {
  position: relative;
  border: 0.5px solid rgb(0, 0, 0);
  width: $socket-size;
  height: $socket-size * 2;
  background: rgb(79, 182, 70);
  box-sizing: border-box;
  background-clip: content-box;

  transform: scale(0.6);

  pointer-events: none;
}

// Area in which the pointer will snap to the socket - partially generated by Gemini Fast
.snap-target {
  pointer-events: none;
  border-radius: 20%;
  background-color: rgba(0, 0, 0, 0);

  width: 40px;
  height: 30px;
  top: -5px;
  left: -15px;
  position: absolute;
  cursor: default;
}
</style>
