<template>
  <div class="snap-target" style="transform: translate(0%, 0%)"></div>
</template>

<script lang="ts">
export default {
  props: ['data']
}
</script>

<style lang="scss" scoped>
@use "sass:math";

// Area in which the pointer will snap to the socket - partially generated by Gemini Fast
.snap-target {
  // pointer-events: none;
  border-radius: 20%;
  background-color: rgba(0, 0, 0, 0);

  width: 40px;
  height: 30px;
  top: -5px;
  left: -15px;
  position: absolute;
  cursor: default;
}
</style>
